---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    description: "Example service template"
    iconClass: "icon-jboss"
  labels: {}
  name: "service-template-dev"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      app: "service-template"
      artifact: "service-template"
      version: "1.0.0-SNAPSHOT"
      group: "com.ofbizian"
    name: "service-template-service"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    loadBalancerIP: ""
    ports:
    - port: 8080
      protocol: "TCP"
      targetPort: 8080
    selector:
      app: "service-template"
    sessionAffinity: "None"
    type: "ClusterIP"
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    annotations: {}
    labels:
      app: "service-template"
      artifact: "service-template"
      version: "1.0-SNAPSHOT"
      group: "com.ofbizian"
    name: "service-template"
  spec:
    dockerImageRepository: ""
    tags: []
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    annotations: {}
    labels:
      app: "service-template"
      artifact: "service-template"
      version: "1.0-SNAPSHOT"
      group: "com.ofbizian"
    name: "service-template"
  spec:
    output:
      to:
        kind: "ImageStreamTag"
        name: "service-template:latest"
    source:
      git:
        ref: "custom-build"
        uri: "https://github.com/bibryam/service-build/"
      images: []
      secrets: []
      type: "Git"
    strategy:
      sourceStrategy:
        env:
        - name: "NEXUS_URL"
          value: "${NEXUS_URL}"
        - name: "REPOSITORY_NAME"
          value: "${REPOSITORY_NAME}"
        - name: "GROUP_ID"
          value: "${GROUP_ID}"
        - name: "ARTIFACT_ID"
          value: "${ARTIFACT_ID}"
        - name: "ARTIFACT_VERSION"
          value: "${ARTIFACT_VERSION}"
        - name: "CLASSIFIER"
          value: "${CLASSIFIER}"
        - name: "EXTENSION"
          value: "${EXTENSION}"
        from:
          kind: "ImageStreamTag"
          name: "fis-java-openshift:latest"
          namespace: "openshift"
        incremental: true
      type: "Source"
    triggers:
    - imageChange:
        from:
          kind: "ImageStreamTag"
          name: "fis-java-openshift:latest"
          namespace: "openshift"
      type: "ImageChange"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    annotations: {}
    labels:
      app: "service-template"
      artifact: "service-template"
      deploymentconfig: "service-template"
      version: "1.0-SNAPSHOT"
      group: "com.ofbizian"
    name: "service-template"
  spec:
    replicas: 1
    selector:
      app: "service-template"
      deploymentconfig: "service-template"
    strategy:
      annotations: {}
      labels: {}
      rollingParams:
        maxSurge: "30%"
        maxUnavailable: "20%"
        timeoutSeconds: 240
      type: "Rolling"
    template:
      metadata:
        annotations: {}
        labels:
          app: "service-template"
          artifact: "service-template"
          deploymentconfig: "service-template"
          version: "1.0-SNAPSHOT"
          group: "com.ofbizian"
      spec:
        containers:
        - args: []
          command: []
          env: []
          image: "service-template"
          imagePullPolicy: "Always"
          livenessProbe:
            exec:
              command:
              - "/bin/bash"
              - "-c"
              - "(curl -f 127.0.0.1:8080) >/dev/null 2>&1; test $? != 7"
            initialDelaySeconds: 30
            timeoutSeconds: 60
          name: "service-template"
          ports:
          - containerPort: 8080
            name: "http"
            protocol: "TCP"
          - containerPort: 8778
            name: "jolokia"
            protocol: "TCP"
          readinessProbe:
            exec:
              command:
              - "/bin/bash"
              - "-c"
              - "(curl -f 127.0.0.1:8080) >/dev/null 2>&1; test $? != 7"
            initialDelaySeconds: 30
            timeoutSeconds: 1
          resources:
            limits:
              memory: "1024Mi"
            requests:
              memory: "512Mi"
          volumeMounts:
          - mountPath: "/etc/configmap"
            name: "service-template-configmap"
            readOnly: true
          - mountPath: "/etc/secret"
            name: "service-template-secret"
            readOnly: true
        imagePullSecrets: []
        nodeSelector: {}
        restartPolicy: "Always"
        volumes:
        - configMap:
            items: []
            name: "service-template"
          name: "service-template-configmap"
        - name: "service-template-secret"
          secret:
            secretName: "service-template"
    triggers:
    - type: "ConfigChange"
    - imageChangeParams:
        automatic: true
        containerNames:
        - "service-template"
        from:
          kind: "ImageStreamTag"
          name: "service-template:latest"
      type: "ImageChange"
- apiVersion: "v1"
  kind: "Route"
  metadata:
    annotations: {}
    labels:
      app: "service-template"
      artifact: "service-template"
      version: "1.0-SNAPSHOT"
      group: "com.ofbizian"
    name: "service-template-route"
  spec:
    to:
      kind: "Service"
      name: "service-template-service"
parameters:
- displayName: "Nexus URL"
  name: "NEXUS_URL"
  value: "http://localhost:8081"
- displayName: "Repository Name"
  name: "REPOSITORY_NAME"
  value: "snapshots"
- displayName: "Group ID"
  name: "GROUP_ID"
  value: "com.ofbizian"
- displayName: "Artifact ID"
  name: "ARTIFACT_ID"
  value: "service-template"
- displayName: "Artifact Version"
  name: "ARTIFACT_VERSION"
  value: "LATEST"
- displayName: "Classifier"
  name: "CLASSIFIER"
  value: "app"
- displayName: "Extension"
  name: "EXTENSION"
  value: "zip"
